sonar.organization=Johnny
sonar.projectKey=JohnnyPlus08_Atividade---Pipeline-Calculadora
sonar.projectName=Atividade - Pipeline Calculadora

# Caminhos do código fonte
sonar.sources=.
sonar.tests=.
sonar.test.exclusions=**/test_*.py, **/*.test.js

# Mapeamento de Linguagens principais
sonar.language=py,js
sonar.sourceEncoding=UTF-8